### ISSUE TITLE
Request: Property Logo Photo Choose from Hard Drive Option

### ISSUE THREAD

**Issue by Tenechtilan** [jonthysell/StarTrekCardMaker#8]
Thanks for the awesome WYSIWYG editor!  Would it be possible to add the ability to choose a photo from your hard drive for the Property Logo section?  Thanks.

**Comment by jonthysell** [comment]
Yes, I will eventually add support for you to specify "custom" alternate images for property logos, expansion icons, etc that get embedded into the card for easy sharing.
